### PR TITLE
Gentoo support

### PR DESCRIPTION
**Pull request by joelbernstein**
Hi, I've added minimal support to use this cookbook on gentoo servers

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @joelbernstein! Thanks for the PR! Could you add a few tests for this?

**Comment by joelbernstein** [comment]
I can do one for the directory creation but Fauxhai has no platform support (https://github.com/customink/fauxhai/tree/master/lib/fauxhai/platforms) for Gentoo. In all honesty I think Gentoo is dreadful but forking your cookbook helped me get a client's task done quicker and I felt it best to feed my fork back. It seems a bit of a yak-shaving exercise to write a platform JSON file by hand for Gentoo. I'll look into whether Fauxhai can capture the platform data easily itself, if so I can do a run on a Gentoo machine to capture the output. What d'you think is best? Would a test against the directory creation be sufficient?

**Comment by sethvargo** [comment]
If you have a Gentoo box you can give to fauxhai, you'll be a hero.

Fauxhai has a cli (fauxhai) that you can run on the client machine which will grab the ohai data and sanitize it for fauxhai. The instructions are in the readme :)

**Comment by sethvargo** [comment]
@joelbernstein (pinging you because sometimes github notifications get strange…)

**Pull request closed without merging**
