### PR TITLE
Fix broken download link

### PR DESCRIPTION
**Pull request by dkubb**
This fixes the download link which has changed recently. It also adds arch specific links and removes the hard coded checksum and makes it configurable.

### CODE REVIEW

**Comment by sethvargo** [comment]
Awesome. I'm not a huge fan of the naming convention for the downloads. Thanks for finding a better way to handle it!

**Comment by sethvargo** [comment]
If submitting requests in the future, please also fix the specs, attributes, README, etc before submitting the PR.

**Comment by dkubb** [comment]
Ahh sorry about that. I've not come across a chef recipe with actual specs other than the ones I write myself internally. I'll make sure to update those next time.

**Comment by sethvargo** [comment]
Yea, while this cookbook does install `phantomjs`, it's major intention (and the reason it was featured on the @foodfight) was because it has a full test suite, as well as `fauxhai` :)

**Pull request merged**
