### PR TITLE
Use ark to download / deploy phantomjs from sources

### PR DESCRIPTION
**Pull request by guilhem**

### CODE REVIEW

**Comment by sethvargo** [comment]
While this greatly simplifies the code, I don't think ark is well-tested. It's also somewhat unclear "what is happening". I'm not particularly a fan of ark's abstraction choices. What's the advantage of using ark?

**Comment by guilhem** [comment]
I'm at the opposite.
IMPOV, ARK is one of the best chef's feature.
It's a good abstraction of a source installation.

for example:
ARK manage versionning
ARK may manage untar better than just "execute this command" ... is this program installed / available? You don't care in your recipe.
ARK manage binary linking. You do assumption that user want "/usr/local/bin"... maybe not always.
And maybe many more!
ARK improve any day without any cost for your cookbook. Key is synergy, not redo (IMPOV).

It's a fundamental way of thinking, I can understand your are not this point of view...

**Comment by sethvargo** [comment]
> ARK improve any day without any cost for your cookbook. Key is synergy, not redo (IMPOV).

That's the part I **don't** like.

**Comment by guilhem** [comment]
I know... that what I speak about "fundamental way of thinking".

Some people see open-source like "I'm happy to touch what I want to".
I see open source like "How to improve mankind by sharing knowledge".

I don't know if one is better than the other. What I know is that we can't be agreed.

**Comment by sethvargo** [comment]
I appreciate your hard work, but I'm not comfortable merging this. Here's my main reason why:

> dependencies change

I don't have a ton of spare time to manage this cookbook, and right now it uses the bare-bones Chef resources. I know when new versions of Chef come out that the cookbook will likely be broken. But each additional dependency introduces another point of potential failure in the future. I don't watch or monitor the ARK cookbook, and I don't really have the bandwidth to do so. 

I really appreciate the improvements, but I'm not sure the simplification is worth the added risks from a software stability standpoint.

**Comment by guilhem** [comment]
I can "understand" this point of view.

This is for the same reason (lack of time) that, for example, zabbix cookbook maintainer give to some trusted people rights to merge.
For the same reason I give ownership to debian cookbook to someone else with more input / time / need.

I see cookbook as a community project, moreover if you put it on community.opscode.com (because no one can put another same-named cookbook).

You don't have time to follow ark... right. But someone who use phantomjs will do.
For your company, you must have another branch like "prod" or something like this if you don't trust your own "master".
But you can't close an improvement by lack of time. Community is here to help you.

**Pull request closed without merging**
