### PR TITLE
Update phantomjs source

### PR DESCRIPTION
**Pull request by sax**
Older packages in the code.google.com site have been recently removed. This commit updates the version of phantomjs to 1.7.0 and changes the format of the base name to reflect the latest available package.

### CODE REVIEW

**Comment by sethvargo** [comment]
@sax this seems to have broken the specs. Can you take a look at that?

**Comment by sax** [comment]
It looks like the specs have been broken since the last pull request (https://travis-ci.org/#!/customink-webops/phantomjs/builds). I'll be happy to look at them, though I'm new to rspec with chef and it may take me a while.

**Comment by sax** [comment]
There appears to be one more failing test, from the previous pull request:
  No package resource named 'fontconfig' with action :install found.

This last commit fixes the tests related to versioning, though.

I'll try to fix the last test and either add it to this pull request or start a new one.

**Comment by sax** [comment]
This pull request (https://github.com/customink-webops/phantomjs/pull/3) uses ohai functionality that was not present in fauxhai at the time. This latest commit updates to latest fauxhai and chefspec in order to make the tests pass.

**Comment by sethvargo** [comment]
Sweet thanks!

**Comment by sax** [comment]
Thanks for merging it! I did not increment the version, as I figured you would want to control that.

**Comment by sethvargo** [comment]
Will do

**Pull request merged**
