### PR TITLE
Update tests to latest best practices

### PR DESCRIPTION
**Pull request by guilhem**
add `Rakefile` for rubocop, foodcritic, stove, TK

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1: on everything but Rubocop

**Comment by guilhem** [comment]
Rubocop is really a _musthave_

We may discuss about rules on/off
But it's really important to look at a code with good (and same) practices and even better, who can signal some dumb errors.

**Comment by sethvargo** [comment]
@guilhem I do not wish to spend time arguing with people over rules; Rubocop has become incredibly opinionated and I don't think some of the author's choices make sense for Chef cookbooks.

**Comment by guilhem** [comment]
@sethvargo Just don't spend time with _simple_ people and seriously go frak.

RuboCop _is_ a _musthave_. If some rules don't fit chef good practice, let's do a `rubocop-chef` custom-{cops|formatter}.
But for the moment, it's a quality seal for cookbook.

**Pull request closed without merging**
